### ISSUE TITLE
Exception: Unexpected response code 404 from Home Assistant API endpoint /api/states/.

### ISSUE THREAD

**Issue by werddomain** [qJake/HADotNet#4]
System.Exception: Unexpected response code 404 from Home Assistant API endpoint /api/states/.
   at HADotNet.Core.BaseClient.Get[T](String path)
   at HADotNet.Core.Clients.StatesClient.GetState(String entityId)
   at Hass_Alarm.Controllers.HomeController.Panel() in D:\HassIo\Hass-Alarm\Hass-Alarm\Controllers\HomeController.cs:line 63

i will test with the source to see where is the error, because the error message dont say much ...

home assistant core version : 0.105.5
operating system: 3.11
Supervisor version : 209

asp.net core 3.0

usage : https://github.com/werddomain/Hass-Alarm/blob/master/Hass-Alarm/Controllers/HomeController.cs

**Comment by werddomain** [comment]
My bad. The entityId was not correct. Sorry. I close this isue.
